# ${projectName}

> This project was reverse-engineered from an APK file using APK2Project.

## Project Information

| Property | Value |
|----------|-------|
| Package Name | `${packageName}` |
| Version Name | ${versionName} |
| Version Code | ${versionCode} |
| Min SDK | ${minSdk} (Android ${minSdkName}) |
| Target SDK | ${targetSdk} (Android ${targetSdkName}) |

## Generation Details

- **Generated on**: ${generatedDate}
- **Source APK**: ${sourceApkName}
- **APK Size**: ${apkSizeMb} MB
- **Total Classes**: ${totalClasses}
- **Decompilation Success Rate**: ${decompileSuccessRate}%

## Detected Dependencies

${dependencyCount} dependencies were automatically detected:

### Core Libraries
<#list coreDependencies as dep>
- `${dep}`
</#list>

### Third-party Libraries
<#list detectedDependencies as dep>
- `${dep.notation}` (${(dep.confidence * 100)?string["0"]}% confidence)
</#list>

## Build Instructions

1. Open this project in Android Studio
2. Sync Gradle files
3. Build the project:

```bash
./gradlew assembleDebug
```

## Known Issues

<#if obfuscated>
### Obfuscation Detected

The original APK was obfuscated using ProGuard/R8. Some class and method names may be unclear (e.g., `a`, `b`, `c`).

</#if>
<#if hasNativeLibraries>
### Native Libraries

This project contains native libraries (.so files). These cannot be decompiled and are included as-is:

<#list nativeLibraries as abi, libs>
- **${abi}**: ${libs?size} libraries
</#list>

</#if>
### Potential Compilation Errors

Some decompiled code may have compilation errors due to:
- Missing dependencies (not all libraries could be detected)
- Obfuscated code patterns
- Incomplete decompilation

Review and fix any compilation errors manually.

## Disclaimer

This project was generated for educational and security research purposes. Ensure you have the legal right to reverse-engineer the original APK.

---

*Generated by [APK2Project](https://github.com/whatap/apk2project)*
